services:
  www:
    image: php7.4-cli
    container_name: projet-www
    ports:
      - 8888:80
    environment: 
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - COMPOSER_ALLOW_SUPERUSER=1
      - DISPLAY_ERRORS=1
    volumes:
      - ./www:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db

  pma:
    image: phpmyadmin
    container_name: projet-phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1024M
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb:latest
    container_name: projet-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/var/lib/mysql