SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Base de données : `demo`
--

--
-- Déchargement des données de la table `pages`
--

INSERT INTO `pages` (`id`, `slug`, `title`, `content`, `created_at`, `updated_at`) VALUES
(1, 'home', 'Home', '<h1>HTML Ipsum Presents</h1>\r\n\r\n				<p><strong>Pellentesque habitant morbi tristique</strong> senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.</em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae</code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim</a> in turpis pulvinar facilisis. Ut felis.</p>\r\n\r\n				<h2>Header Level 2</h2>\r\n\r\n				<ol>\r\n				   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>\r\n				   <li>Aliquam tincidunt mauris eu risus.</li>\r\n				</ol>\r\n\r\n				<blockquote><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in mi at felis aliquet congue. Ut a est eget ligula molestie gravida. Curabitur massa. Donec eleifend, libero at sagittis mollis, tellus est malesuada tellus, at luctus turpis elit sit amet quam. Vivamus pretium ornare est.</p></blockquote>\r\n\r\n				<h3>Header Level 3</h3>\r\n\r\n				<ul>\r\n				   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>\r\n				   <li>Aliquam tincidunt mauris eu risus.</li>\r\n				</ul>\r\n\r\n				<pre><code>\r\n				#header h1 a {\r\n				  display: block;\r\n				  width: 300px;\r\n				  height: 80px;\r\n				}\r\n				</code></pre>', '2022-04-06 05:10:40', '2022-04-06 05:10:40'),
(2, 'who-am-i', 'Who Am I ?', '<h1>HTML Ipsum Presents</h1>\r\n\r\n				<p><strong>Pellentesque habitant morbi tristique</strong> senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.</em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae</code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href=\"#\">Donec non enim</a> in turpis pulvinar facilisis. Ut felis.</p>\r\n\r\n				<h2>Header Level 2</h2>\r\n\r\n				<ol>\r\n				   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>\r\n				   <li>Aliquam tincidunt mauris eu risus.</li>\r\n				</ol>\r\n\r\n				<blockquote><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in mi at felis aliquet congue. Ut a est eget ligula molestie gravida. Curabitur massa. Donec eleifend, libero at sagittis mollis, tellus est malesuada tellus, at luctus turpis elit sit amet quam. Vivamus pretium ornare est.</p></blockquote>\r\n\r\n				<h3>Header Level 3</h3>\r\n\r\n				<ul>\r\n				   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>\r\n				   <li>Aliquam tincidunt mauris eu risus.</li>\r\n				</ul>\r\n\r\n				<pre><code>\r\n				#header h1 a {\r\n				  display: block;\r\n				  width: 300px;\r\n				  height: 80px;\r\n				}\r\n				</code></pre>', '2022-04-06 05:10:40', '2022-04-06 05:10:40'),
(3, 'get-in-touch', 'Get in touch', '<form action=\"#\" method=\"post\">\r\n					<div>\r\n						 <label for=\"name\">Text Input:</label>\r\n						 <input type=\"text\" name=\"name\" id=\"name\" value=\"\" tabindex=\"1\" />\r\n					</div>\r\n\r\n					<div>\r\n						 <h4>Radio Button Choice</h4>\r\n\r\n						 <label for=\"radio-choice-1\">Choice 1</label>\r\n						 <input type=\"radio\" name=\"radio-choice-1\" id=\"radio-choice-1\" tabindex=\"2\" value=\"choice-1\" />\r\n\r\n					 <label for=\"radio-choice-2\">Choice 2</label>\r\n						 <input type=\"radio\" name=\"radio-choice-2\" id=\"radio-choice-2\" tabindex=\"3\" value=\"choice-2\" />\r\n					</div>\r\n\r\n				  <div>\r\n					<label for=\"select-choice\">Select Dropdown Choice:</label>\r\n					<select name=\"select-choice\" id=\"select-choice\">\r\n					  <option value=\"Choice 1\">Choice 1</option>\r\n					  <option value=\"Choice 2\">Choice 2</option>\r\n					  <option value=\"Choice 3\">Choice 3</option>\r\n					</select>\r\n				  </div>\r\n\r\n				  <div>\r\n					<label for=\"textarea\">Textarea:</label>\r\n					<textarea cols=\"40\" rows=\"8\" name=\"textarea\" id=\"textarea\"></textarea>\r\n				  </div>\r\n\r\n				  <div>\r\n					  <label for=\"checkbox\">Checkbox:</label>\r\n					<input type=\"checkbox\" name=\"checkbox\" id=\"checkbox\" />\r\n					</div>\r\n\r\n				  <div>\r\n					  <input type=\"submit\" value=\"Submit\" />\r\n					</div>\r\n				</form>', '2022-04-06 05:10:40', '2022-04-06 05:10:40'),
(4, 'news', 'What\'s up ?', '				<ul>\r\n				   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>\r\n				   <li>Aliquam tincidunt mauris eu risus.</li>\r\n				   <li>Vestibulum auctor dapibus neque.</li>\r\n				</ul>\r\n						 ', '2022-04-06 05:10:40', '2022-04-06 05:10:40');

--
-- Déchargement des données de la table `posts`
--

INSERT INTO `posts` (`id`, `slug`, `title`, `content`, `created_at`, `updated_at`) VALUES
(1, 'new-website', 'Here is my new website !', '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>', '2022-04-06 05:12:52', '2022-04-06 05:12:52'),
(2, 'lorem-ipsum', 'lorem-ipsum', '<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\r\n<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>\r\n<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.</p>', '2022-04-06 05:12:52', '2022-04-06 05:13:12');
COMMIT;
